# This is a basic workflow to help you get started with Actions

name: Automate Script

on:
  schedule:
    - cron: '0 */2 * * *'  # This schedule runs the job every 2 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with your Python version

      - name: Install Dependencies
        run: |
          pip install pdf2image
          pip install requests
          pip install Pillow
          pip install bs4

      - name: Run Python Script
        run: python your_script_name.py  # Replace with your script name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

